// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: blocks.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getIndexedBlockByHash = `-- name: GetIndexedBlockByHash :one
SELECT chain_id, block_number, block_hash, parent_hash, block_time, finality_status
FROM indexed_blocks
WHERE chain_id = $1 AND block_hash = $2
`

type GetIndexedBlockByHashParams struct {
	ChainID   int64
	BlockHash Hash
}

func (q *Queries) GetIndexedBlockByHash(ctx context.Context, arg GetIndexedBlockByHashParams) (IndexedBlock, error) {
	row := q.db.QueryRow(ctx, getIndexedBlockByHash, arg.ChainID, arg.BlockHash)
	var i IndexedBlock
	err := row.Scan(
		&i.ChainID,
		&i.BlockNumber,
		&i.BlockHash,
		&i.ParentHash,
		&i.BlockTime,
		&i.FinalityStatus,
	)
	return i, err
}

const getIndexedBlockByNumber = `-- name: GetIndexedBlockByNumber :one
SELECT chain_id, block_number, block_hash, parent_hash, block_time, finality_status
FROM indexed_blocks
WHERE chain_id = $1 AND block_number = $2
`

type GetIndexedBlockByNumberParams struct {
	ChainID     int64
	BlockNumber int64
}

func (q *Queries) GetIndexedBlockByNumber(ctx context.Context, arg GetIndexedBlockByNumberParams) (IndexedBlock, error) {
	row := q.db.QueryRow(ctx, getIndexedBlockByNumber, arg.ChainID, arg.BlockNumber)
	var i IndexedBlock
	err := row.Scan(
		&i.ChainID,
		&i.BlockNumber,
		&i.BlockHash,
		&i.ParentHash,
		&i.BlockTime,
		&i.FinalityStatus,
	)
	return i, err
}

const promoteIndexedBlocks = `-- name: PromoteIndexedBlocks :exec
UPDATE indexed_blocks
SET finality_status = CASE
 WHEN $3 = 'finalized' THEN 'finalized'
 WHEN finality_status = 'finalized' THEN 'finalized'
 ELSE 'safe'
END
WHERE chain_id=$1 AND block_number > $4 AND block_number <= $2
`

type PromoteIndexedBlocksParams struct {
	ChainID       int64
	BlockNumber   int64
	Column3       interface{}
	BlockNumber_2 int64
}

func (q *Queries) PromoteIndexedBlocks(ctx context.Context, arg PromoteIndexedBlocksParams) error {
	_, err := q.db.Exec(ctx, promoteIndexedBlocks,
		arg.ChainID,
		arg.BlockNumber,
		arg.Column3,
		arg.BlockNumber_2,
	)
	return err
}

const upsertIndexedBlock = `-- name: UpsertIndexedBlock :execrows
INSERT INTO indexed_blocks (
    chain_id,
    block_number,
    block_hash,
    parent_hash,
    block_time,
    finality_status
) VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (chain_id, block_number) DO UPDATE
SET finality_status = EXCLUDED.finality_status
WHERE indexed_blocks.block_hash = EXCLUDED.block_hash
  AND indexed_blocks.parent_hash = EXCLUDED.parent_hash
  AND indexed_blocks.block_time = EXCLUDED.block_time
`

type UpsertIndexedBlockParams struct {
	ChainID        int64
	BlockNumber    int64
	BlockHash      Hash
	ParentHash     Hash
	BlockTime      pgtype.Timestamptz
	FinalityStatus string
}

func (q *Queries) UpsertIndexedBlock(ctx context.Context, arg UpsertIndexedBlockParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertIndexedBlock,
		arg.ChainID,
		arg.BlockNumber,
		arg.BlockHash,
		arg.ParentHash,
		arg.BlockTime,
		arg.FinalityStatus,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
