// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLaunchPauseEventByIdentity = `-- name: GetLaunchPauseEventByIdentity :one
SELECT chain_id, block_number, block_hash, block_time, transaction_index, tx_hash, log_index, paused
FROM launch_pause_events
WHERE chain_id = $1 AND tx_hash = $2 AND log_index = $3
`

type GetLaunchPauseEventByIdentityParams struct {
	ChainID  int64
	TxHash   Hash
	LogIndex int32
}

func (q *Queries) GetLaunchPauseEventByIdentity(ctx context.Context, arg GetLaunchPauseEventByIdentityParams) (LaunchPauseEvent, error) {
	row := q.db.QueryRow(ctx, getLaunchPauseEventByIdentity, arg.ChainID, arg.TxHash, arg.LogIndex)
	var i LaunchPauseEvent
	err := row.Scan(
		&i.ChainID,
		&i.BlockNumber,
		&i.BlockHash,
		&i.BlockTime,
		&i.TransactionIndex,
		&i.TxHash,
		&i.LogIndex,
		&i.Paused,
	)
	return i, err
}

const getTradeByEventIdentity = `-- name: GetTradeByEventIdentity :one
SELECT
    chain_id, block_number, block_hash, block_time, transaction_index, tx_hash, log_index,
    token_address, trader, is_buy, eth_gross, eth_refund, token_amount, protocol_fee,
    creator_fee, new_eth_reserve, new_token_reserve
FROM trades
WHERE chain_id = $1 AND tx_hash = $2 AND log_index = $3
`

type GetTradeByEventIdentityParams struct {
	ChainID  int64
	TxHash   Hash
	LogIndex int32
}

func (q *Queries) GetTradeByEventIdentity(ctx context.Context, arg GetTradeByEventIdentityParams) (Trade, error) {
	row := q.db.QueryRow(ctx, getTradeByEventIdentity, arg.ChainID, arg.TxHash, arg.LogIndex)
	var i Trade
	err := row.Scan(
		&i.ChainID,
		&i.BlockNumber,
		&i.BlockHash,
		&i.BlockTime,
		&i.TransactionIndex,
		&i.TxHash,
		&i.LogIndex,
		&i.TokenAddress,
		&i.Trader,
		&i.IsBuy,
		&i.EthGross,
		&i.EthRefund,
		&i.TokenAmount,
		&i.ProtocolFee,
		&i.CreatorFee,
		&i.NewEthReserve,
		&i.NewTokenReserve,
	)
	return i, err
}

const insertLaunchPauseEvent = `-- name: InsertLaunchPauseEvent :execrows
INSERT INTO launch_pause_events (
    chain_id, block_number, block_hash, block_time, transaction_index, tx_hash, log_index, paused
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (chain_id, tx_hash, log_index) DO NOTHING
`

type InsertLaunchPauseEventParams struct {
	ChainID          int64
	BlockNumber      int64
	BlockHash        Hash
	BlockTime        pgtype.Timestamptz
	TransactionIndex int32
	TxHash           Hash
	LogIndex         int32
	Paused           bool
}

func (q *Queries) InsertLaunchPauseEvent(ctx context.Context, arg InsertLaunchPauseEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertLaunchPauseEvent,
		arg.ChainID,
		arg.BlockNumber,
		arg.BlockHash,
		arg.BlockTime,
		arg.TransactionIndex,
		arg.TxHash,
		arg.LogIndex,
		arg.Paused,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertTrade = `-- name: InsertTrade :execrows
INSERT INTO trades (
    chain_id, block_number, block_hash, block_time, transaction_index, tx_hash, log_index,
    token_address, trader, is_buy, eth_gross, eth_refund, token_amount, protocol_fee,
    creator_fee, new_eth_reserve, new_token_reserve
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11, $12, $13, $14,
    $15, $16, $17
)
ON CONFLICT (chain_id, tx_hash, log_index) DO NOTHING
`

type InsertTradeParams struct {
	ChainID          int64
	BlockNumber      int64
	BlockHash        Hash
	BlockTime        pgtype.Timestamptz
	TransactionIndex int32
	TxHash           Hash
	LogIndex         int32
	TokenAddress     Address
	Trader           Address
	IsBuy            bool
	EthGross         Uint256
	EthRefund        Uint256
	TokenAmount      Uint256
	ProtocolFee      Uint256
	CreatorFee       Uint256
	NewEthReserve    Uint256
	NewTokenReserve  Uint256
}

func (q *Queries) InsertTrade(ctx context.Context, arg InsertTradeParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertTrade,
		arg.ChainID,
		arg.BlockNumber,
		arg.BlockHash,
		arg.BlockTime,
		arg.TransactionIndex,
		arg.TxHash,
		arg.LogIndex,
		arg.TokenAddress,
		arg.Trader,
		arg.IsBuy,
		arg.EthGross,
		arg.EthRefund,
		arg.TokenAmount,
		arg.ProtocolFee,
		arg.CreatorFee,
		arg.NewEthReserve,
		arg.NewTokenReserve,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
