// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: indexer.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listTokenIdentities = `-- name: ListTokenIdentities :many
SELECT token_address, curve_address, lp_pair, engine_version,
       launch_block_number, launch_block_hash, launch_block_time
FROM tokens WHERE chain_id=$1 ORDER BY token_address
`

type ListTokenIdentitiesRow struct {
	TokenAddress      Address
	CurveAddress      Address
	LpPair            Address
	EngineVersion     int32
	LaunchBlockNumber int64
	LaunchBlockHash   Hash
	LaunchBlockTime   pgtype.Timestamptz
}

func (q *Queries) ListTokenIdentities(ctx context.Context, chainID int64) ([]ListTokenIdentitiesRow, error) {
	rows, err := q.db.Query(ctx, listTokenIdentities, chainID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTokenIdentitiesRow{}
	for rows.Next() {
		var i ListTokenIdentitiesRow
		if err := rows.Scan(
			&i.TokenAddress,
			&i.CurveAddress,
			&i.LpPair,
			&i.EngineVersion,
			&i.LaunchBlockNumber,
			&i.LaunchBlockHash,
			&i.LaunchBlockTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTokenPhaseCounts = `-- name: ListTokenPhaseCounts :many
SELECT token.phase, count(*)::BIGINT AS token_count
FROM tokens AS token
WHERE token.chain_id = $1
GROUP BY token.phase
ORDER BY token.phase
`

type ListTokenPhaseCountsRow struct {
	Phase      string
	TokenCount int64
}

func (q *Queries) ListTokenPhaseCounts(ctx context.Context, chainID int64) ([]ListTokenPhaseCountsRow, error) {
	rows, err := q.db.Query(ctx, listTokenPhaseCounts, chainID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTokenPhaseCountsRow{}
	for rows.Next() {
		var i ListTokenPhaseCountsRow
		if err := rows.Scan(&i.Phase, &i.TokenCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readOperationalHealth = `-- name: ReadOperationalHealth :one
SELECT
    dirty.dirty_work,
    COALESCE(reorg.reorg_id, 0)::BIGINT AS last_reorg_id,
    COALESCE(reorg.depth, 0)::BIGINT AS last_reorg_depth,
    reorg.detected_at AS last_reorg_at
FROM (SELECT count(*)::BIGINT AS dirty_work FROM aggregation_dirty AS entry WHERE entry.chain_id = $1) AS dirty
LEFT JOIN LATERAL (
    SELECT reorg_id, depth, detected_at
    FROM indexer_reorgs AS entry
    WHERE entry.chain_id = $1 AND entry.deployment_id = $2
    ORDER BY reorg_id DESC
    LIMIT 1
) AS reorg ON TRUE
`

type ReadOperationalHealthParams struct {
	ChainID      int64
	DeploymentID string
}

type ReadOperationalHealthRow struct {
	DirtyWork      int64
	LastReorgID    int64
	LastReorgDepth int64
	LastReorgAt    pgtype.Timestamptz
}

func (q *Queries) ReadOperationalHealth(ctx context.Context, arg ReadOperationalHealthParams) (ReadOperationalHealthRow, error) {
	row := q.db.QueryRow(ctx, readOperationalHealth, arg.ChainID, arg.DeploymentID)
	var i ReadOperationalHealthRow
	err := row.Scan(
		&i.DirtyWork,
		&i.LastReorgID,
		&i.LastReorgDepth,
		&i.LastReorgAt,
	)
	return i, err
}
