// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: indexer.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listTokenIdentities = `-- name: ListTokenIdentities :many
SELECT token_address, curve_address, lp_pair, engine_version,
       launch_block_number, launch_block_hash, launch_block_time
FROM tokens WHERE chain_id=$1 ORDER BY token_address
`

type ListTokenIdentitiesRow struct {
	TokenAddress      Address
	CurveAddress      Address
	LpPair            Address
	EngineVersion     int32
	LaunchBlockNumber int64
	LaunchBlockHash   Hash
	LaunchBlockTime   pgtype.Timestamptz
}

func (q *Queries) ListTokenIdentities(ctx context.Context, chainID int64) ([]ListTokenIdentitiesRow, error) {
	rows, err := q.db.Query(ctx, listTokenIdentities, chainID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTokenIdentitiesRow{}
	for rows.Next() {
		var i ListTokenIdentitiesRow
		if err := rows.Scan(
			&i.TokenAddress,
			&i.CurveAddress,
			&i.LpPair,
			&i.EngineVersion,
			&i.LaunchBlockNumber,
			&i.LaunchBlockHash,
			&i.LaunchBlockTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
