// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: metadata.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const replaceTokenImage = `-- name: ReplaceTokenImage :one
INSERT INTO token_images (chain_id, token_address, content_type, content, byte_size, sha256, revision, updated_at)
SELECT $1, $2, $3, $4,
       $5, $6, 0, $7
FROM tokens
WHERE chain_id = $1 AND token_address = $2
  AND creator = $8 AND $9::bigint = 0
ON CONFLICT (chain_id, token_address) DO UPDATE
SET content_type = EXCLUDED.content_type, content = EXCLUDED.content,
    byte_size = EXCLUDED.byte_size, sha256 = EXCLUDED.sha256,
    revision = token_images.revision + 1, updated_at = EXCLUDED.updated_at
WHERE token_images.revision = $9
RETURNING revision
`

type ReplaceTokenImageParams struct {
	ChainID          int64
	TokenAddress     Address
	ContentType      string
	Content          []byte
	ByteSize         int32
	Sha256           Hash
	UpdatedAt        pgtype.Timestamptz
	Creator          Address
	ExpectedRevision int64
}

func (q *Queries) ReplaceTokenImage(ctx context.Context, arg ReplaceTokenImageParams) (int64, error) {
	row := q.db.QueryRow(ctx, replaceTokenImage,
		arg.ChainID,
		arg.TokenAddress,
		arg.ContentType,
		arg.Content,
		arg.ByteSize,
		arg.Sha256,
		arg.UpdatedAt,
		arg.Creator,
		arg.ExpectedRevision,
	)
	var revision int64
	err := row.Scan(&revision)
	return revision, err
}

const replaceTokenMetadata = `-- name: ReplaceTokenMetadata :one
INSERT INTO token_metadata (chain_id, token_address, description, image_url, x_url, telegram_url, revision, updated_at)
SELECT $1, $2, $3, $4,
       $5, $6, 0, $7
FROM tokens
WHERE chain_id = $1 AND token_address = $2
  AND creator = $8 AND $9::bigint = 0
ON CONFLICT (chain_id, token_address) DO UPDATE
SET description = EXCLUDED.description, image_url = EXCLUDED.image_url,
    x_url = EXCLUDED.x_url, telegram_url = EXCLUDED.telegram_url,
    revision = token_metadata.revision + 1, updated_at = EXCLUDED.updated_at
WHERE token_metadata.revision = $9
RETURNING revision
`

type ReplaceTokenMetadataParams struct {
	ChainID          int64
	TokenAddress     Address
	Description      pgtype.Text
	ImageUrl         pgtype.Text
	XUrl             pgtype.Text
	TelegramUrl      pgtype.Text
	UpdatedAt        pgtype.Timestamptz
	Creator          Address
	ExpectedRevision int64
}

func (q *Queries) ReplaceTokenMetadata(ctx context.Context, arg ReplaceTokenMetadataParams) (int64, error) {
	row := q.db.QueryRow(ctx, replaceTokenMetadata,
		arg.ChainID,
		arg.TokenAddress,
		arg.Description,
		arg.ImageUrl,
		arg.XUrl,
		arg.TelegramUrl,
		arg.UpdatedAt,
		arg.Creator,
		arg.ExpectedRevision,
	)
	var revision int64
	err := row.Scan(&revision)
	return revision, err
}
