// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: metadata.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTokenCreatorForUpdate = `-- name: GetTokenCreatorForUpdate :one
SELECT creator
FROM token_launches
WHERE chain_id = $1 AND token_address = $2
FOR SHARE
`

type GetTokenCreatorForUpdateParams struct {
	ChainID      int64
	TokenAddress Address
}

func (q *Queries) GetTokenCreatorForUpdate(ctx context.Context, arg GetTokenCreatorForUpdateParams) (Address, error) {
	row := q.db.QueryRow(ctx, getTokenCreatorForUpdate, arg.ChainID, arg.TokenAddress)
	var creator Address
	err := row.Scan(&creator)
	return creator, err
}

const getTokenImage = `-- name: GetTokenImage :one
SELECT content_type, content, sha256, revision, updated_at
FROM token_images AS image
JOIN token_launches AS launch
  ON launch.chain_id = image.chain_id
 AND launch.token_address = image.token_address
 AND launch.tx_hash = image.launch_tx_hash
 AND launch.log_index = image.launch_log_index
WHERE image.chain_id = $1 AND image.token_address = $2
`

type GetTokenImageParams struct {
	ChainID      int64
	TokenAddress Address
}

type GetTokenImageRow struct {
	ContentType string
	Content     []byte
	Sha256      Hash
	Revision    int64
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) GetTokenImage(ctx context.Context, arg GetTokenImageParams) (GetTokenImageRow, error) {
	row := q.db.QueryRow(ctx, getTokenImage, arg.ChainID, arg.TokenAddress)
	var i GetTokenImageRow
	err := row.Scan(
		&i.ContentType,
		&i.Content,
		&i.Sha256,
		&i.Revision,
		&i.UpdatedAt,
	)
	return i, err
}

const getTokenMetadata = `-- name: GetTokenMetadata :one
SELECT description, image_url, x_url, telegram_url, revision, updated_at
FROM token_metadata AS metadata
JOIN token_launches AS launch
  ON launch.chain_id = metadata.chain_id
 AND launch.token_address = metadata.token_address
 AND launch.tx_hash = metadata.launch_tx_hash
 AND launch.log_index = metadata.launch_log_index
WHERE metadata.chain_id = $1 AND metadata.token_address = $2
`

type GetTokenMetadataParams struct {
	ChainID      int64
	TokenAddress Address
}

type GetTokenMetadataRow struct {
	Description pgtype.Text
	ImageUrl    pgtype.Text
	XUrl        pgtype.Text
	TelegramUrl pgtype.Text
	Revision    int64
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) GetTokenMetadata(ctx context.Context, arg GetTokenMetadataParams) (GetTokenMetadataRow, error) {
	row := q.db.QueryRow(ctx, getTokenMetadata, arg.ChainID, arg.TokenAddress)
	var i GetTokenMetadataRow
	err := row.Scan(
		&i.Description,
		&i.ImageUrl,
		&i.XUrl,
		&i.TelegramUrl,
		&i.Revision,
		&i.UpdatedAt,
	)
	return i, err
}

const replaceTokenImage = `-- name: ReplaceTokenImage :one
INSERT INTO token_images (chain_id, token_address, launch_tx_hash, launch_log_index, content_type, content, byte_size, sha256, revision, updated_at)
SELECT launch.chain_id, launch.token_address, launch.tx_hash, launch.log_index,
       $1, $2, $3, $4, 1, $5
FROM token_launches AS launch
WHERE launch.chain_id = $6 AND launch.token_address = $7
  AND launch.creator = $8
  AND ($9::bigint = 0 OR EXISTS (
      SELECT 1 FROM token_images
      WHERE chain_id = launch.chain_id AND token_address = launch.token_address
        AND launch_tx_hash = launch.tx_hash AND launch_log_index = launch.log_index
  ))
ON CONFLICT (chain_id, token_address, launch_tx_hash, launch_log_index)
WHERE launch_tx_hash IS NOT NULL AND launch_log_index IS NOT NULL DO UPDATE
SET content_type = EXCLUDED.content_type, content = EXCLUDED.content,
    byte_size = EXCLUDED.byte_size, sha256 = EXCLUDED.sha256,
    revision = token_images.revision + 1, updated_at = EXCLUDED.updated_at
WHERE token_images.revision = $9
RETURNING revision
`

type ReplaceTokenImageParams struct {
	ContentType      string
	Content          []byte
	ByteSize         int32
	Sha256           Hash
	UpdatedAt        pgtype.Timestamptz
	ChainID          int64
	TokenAddress     Address
	Creator          Address
	ExpectedRevision int64
}

func (q *Queries) ReplaceTokenImage(ctx context.Context, arg ReplaceTokenImageParams) (int64, error) {
	row := q.db.QueryRow(ctx, replaceTokenImage,
		arg.ContentType,
		arg.Content,
		arg.ByteSize,
		arg.Sha256,
		arg.UpdatedAt,
		arg.ChainID,
		arg.TokenAddress,
		arg.Creator,
		arg.ExpectedRevision,
	)
	var revision int64
	err := row.Scan(&revision)
	return revision, err
}

const replaceTokenMetadata = `-- name: ReplaceTokenMetadata :one
INSERT INTO token_metadata (chain_id, token_address, launch_tx_hash, launch_log_index, description, image_url, x_url, telegram_url, revision, updated_at)
SELECT launch.chain_id, launch.token_address, launch.tx_hash, launch.log_index,
       $1, $2, $3, $4, 1, $5
FROM token_launches AS launch
WHERE launch.chain_id = $6 AND launch.token_address = $7
  AND launch.creator = $8
  AND ($9::bigint = 0 OR EXISTS (
      SELECT 1 FROM token_metadata
      WHERE chain_id = launch.chain_id AND token_address = launch.token_address
        AND launch_tx_hash = launch.tx_hash AND launch_log_index = launch.log_index
  ))
ON CONFLICT (chain_id, token_address, launch_tx_hash, launch_log_index)
WHERE launch_tx_hash IS NOT NULL AND launch_log_index IS NOT NULL DO UPDATE
SET description = EXCLUDED.description, image_url = EXCLUDED.image_url,
    x_url = EXCLUDED.x_url, telegram_url = EXCLUDED.telegram_url,
    revision = token_metadata.revision + 1, updated_at = EXCLUDED.updated_at
WHERE token_metadata.revision = $9
RETURNING revision
`

type ReplaceTokenMetadataParams struct {
	Description      pgtype.Text
	ImageUrl         pgtype.Text
	XUrl             pgtype.Text
	TelegramUrl      pgtype.Text
	UpdatedAt        pgtype.Timestamptz
	ChainID          int64
	TokenAddress     Address
	Creator          Address
	ExpectedRevision int64
}

func (q *Queries) ReplaceTokenMetadata(ctx context.Context, arg ReplaceTokenMetadataParams) (int64, error) {
	row := q.db.QueryRow(ctx, replaceTokenMetadata,
		arg.Description,
		arg.ImageUrl,
		arg.XUrl,
		arg.TelegramUrl,
		arg.UpdatedAt,
		arg.ChainID,
		arg.TokenAddress,
		arg.Creator,
		arg.ExpectedRevision,
	)
	var revision int64
	err := row.Scan(&revision)
	return revision, err
}
