// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profile.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listProfileActions = `-- name: ListProfileActions :many
SELECT t.token_address, t.curve_address, t.name, t.symbol, t.phase,
       CASE WHEN t.creator = ANY($1::bytea[]) THEN GREATEST(
           COALESCE((SELECT sum(trade.creator_fee) FROM trades AS trade
                     WHERE trade.chain_id = t.chain_id AND trade.token_address = t.token_address), 0::numeric)
           - COALESCE((SELECT sum(claim.amount) FROM creator_fee_claims AS claim
                       WHERE claim.chain_id = t.chain_id AND claim.token_address = t.token_address), 0::numeric),
           0::numeric
       ) ELSE 0::numeric END::numeric(78, 0) AS creator_fee_amount,
       GREATEST(
           COALESCE((SELECT sum(credit.amount) FROM refund_credits AS credit
                     WHERE credit.chain_id = t.chain_id AND credit.token_address = t.token_address
                       AND credit.account = ANY($1::bytea[])), 0::numeric)
           - COALESCE((SELECT sum(claim.amount) FROM refund_claims AS claim
                       WHERE claim.chain_id = t.chain_id AND claim.token_address = t.token_address
                         AND claim.account = ANY($1::bytea[])), 0::numeric),
           0::numeric
       )::numeric(78, 0) AS refund_amount
FROM tokens AS t
WHERE t.chain_id = $2
  AND (
      (t.creator = ANY($1::bytea[])
       AND COALESCE((SELECT sum(trade.creator_fee) FROM trades AS trade
                     WHERE trade.chain_id = t.chain_id AND trade.token_address = t.token_address), 0::numeric)
           - COALESCE((SELECT sum(claim.amount) FROM creator_fee_claims AS claim
                       WHERE claim.chain_id = t.chain_id AND claim.token_address = t.token_address), 0::numeric) > 0)
      OR
      (COALESCE((SELECT sum(credit.amount) FROM refund_credits AS credit
                 WHERE credit.chain_id = t.chain_id AND credit.token_address = t.token_address
                   AND credit.account = ANY($1::bytea[])), 0::numeric)
       - COALESCE((SELECT sum(claim.amount) FROM refund_claims AS claim
                   WHERE claim.chain_id = t.chain_id AND claim.token_address = t.token_address
                     AND claim.account = ANY($1::bytea[])), 0::numeric) > 0)
  )
ORDER BY t.token_address ASC
`

type ListProfileActionsParams struct {
	Wallets [][]byte
	ChainID int64
}

type ListProfileActionsRow struct {
	TokenAddress     Address
	CurveAddress     Address
	Name             string
	Symbol           string
	Phase            string
	CreatorFeeAmount pgtype.Numeric
	RefundAmount     pgtype.Numeric
}

func (q *Queries) ListProfileActions(ctx context.Context, arg ListProfileActionsParams) ([]ListProfileActionsRow, error) {
	rows, err := q.db.Query(ctx, listProfileActions, arg.Wallets, arg.ChainID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProfileActionsRow{}
	for rows.Next() {
		var i ListProfileActionsRow
		if err := rows.Scan(
			&i.TokenAddress,
			&i.CurveAddress,
			&i.Name,
			&i.Symbol,
			&i.Phase,
			&i.CreatorFeeAmount,
			&i.RefundAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
