// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projections.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimAggregationDirty = `-- name: ClaimAggregationDirty :many
WITH candidate AS (
    SELECT chain_id, token_address
    FROM aggregation_dirty
    WHERE claimed_generation IS NULL OR claimed_generation < generation
    ORDER BY generation, chain_id, token_address
    LIMIT $2::integer
    FOR UPDATE SKIP LOCKED
)
UPDATE aggregation_dirty AS dirty
SET claimed_generation = dirty.generation,
    claimed_at = now(),
    claimed_by = $1
FROM candidate
WHERE dirty.chain_id = candidate.chain_id
  AND dirty.token_address = candidate.token_address
RETURNING dirty.chain_id, dirty.token_address, dirty.claimed_generation
`

type ClaimAggregationDirtyParams struct {
	WorkerID  pgtype.Text
	BatchSize int32
}

type ClaimAggregationDirtyRow struct {
	ChainID           int64
	TokenAddress      Address
	ClaimedGeneration pgtype.Int8
}

func (q *Queries) ClaimAggregationDirty(ctx context.Context, arg ClaimAggregationDirtyParams) ([]ClaimAggregationDirtyRow, error) {
	rows, err := q.db.Query(ctx, claimAggregationDirty, arg.WorkerID, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimAggregationDirtyRow{}
	for rows.Next() {
		var i ClaimAggregationDirtyRow
		if err := rows.Scan(&i.ChainID, &i.TokenAddress, &i.ClaimedGeneration); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const completeAggregationDirty = `-- name: CompleteAggregationDirty :execrows
DELETE FROM aggregation_dirty
WHERE chain_id = $1
  AND token_address = $2
  AND generation = $3
  AND claimed_generation = $3
  AND claimed_by = $4
`

type CompleteAggregationDirtyParams struct {
	ChainID           int64
	TokenAddress      Address
	ClaimedGeneration int64
	WorkerID          pgtype.Text
}

func (q *Queries) CompleteAggregationDirty(ctx context.Context, arg CompleteAggregationDirtyParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeAggregationDirty,
		arg.ChainID,
		arg.TokenAddress,
		arg.ClaimedGeneration,
		arg.WorkerID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rebuildTokenProjections = `-- name: RebuildTokenProjections :exec
SELECT rebuild_token_projections($1, $2)
`

type RebuildTokenProjectionsParams struct {
	RebuildChainID      int64
	RebuildTokenAddress []byte
}

func (q *Queries) RebuildTokenProjections(ctx context.Context, arg RebuildTokenProjectionsParams) error {
	_, err := q.db.Exec(ctx, rebuildTokenProjections, arg.RebuildChainID, arg.RebuildTokenAddress)
	return err
}
