// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	ClaimAggregationDirty(ctx context.Context, arg ClaimAggregationDirtyParams) ([]ClaimAggregationDirtyRow, error)
	CompleteAggregationDirty(ctx context.Context, arg CompleteAggregationDirtyParams) (int64, error)
	GetIndexedBlockByHash(ctx context.Context, arg GetIndexedBlockByHashParams) (IndexedBlock, error)
	GetIndexedBlockByNumber(ctx context.Context, arg GetIndexedBlockByNumberParams) (IndexedBlock, error)
	GetLaunchPauseEventByIdentity(ctx context.Context, arg GetLaunchPauseEventByIdentityParams) (LaunchPauseEvent, error)
	GetSyncState(ctx context.Context, arg GetSyncStateParams) (SyncState, error)
	GetTradeByEventIdentity(ctx context.Context, arg GetTradeByEventIdentityParams) (Trade, error)
	InsertLaunchPauseEvent(ctx context.Context, arg InsertLaunchPauseEventParams) (int64, error)
	InsertTrade(ctx context.Context, arg InsertTradeParams) (int64, error)
	RebuildTokenProjections(ctx context.Context, arg RebuildTokenProjectionsParams) error
	UpsertIndexedBlock(ctx context.Context, arg UpsertIndexedBlockParams) (int64, error)
	UpsertSyncState(ctx context.Context, arg UpsertSyncStateParams) (SyncState, error)
}

var _ Querier = (*Queries)(nil)
