// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reorg.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const affectedTokensAbove = `-- name: AffectedTokensAbove :many
SELECT DISTINCT affected.token_address FROM (
    SELECT launch.token_address FROM token_launches AS launch WHERE launch.chain_id=$1 AND launch.block_number>$2
    UNION ALL SELECT trade.token_address FROM trades AS trade WHERE trade.chain_id=$1 AND trade.block_number>$2
    UNION ALL SELECT graduation.token_address FROM graduations AS graduation WHERE graduation.chain_id=$1 AND graduation.block_number>$2
    UNION ALL SELECT claim.token_address FROM creator_fee_claims AS claim WHERE claim.chain_id=$1 AND claim.block_number>$2
    UNION ALL SELECT claim.token_address FROM protocol_fee_claims AS claim WHERE claim.chain_id=$1 AND claim.block_number>$2
    UNION ALL SELECT credit.token_address FROM refund_credits AS credit WHERE credit.chain_id=$1 AND credit.block_number>$2
    UNION ALL SELECT claim.token_address FROM refund_claims AS claim WHERE claim.chain_id=$1 AND claim.block_number>$2
    UNION ALL SELECT transfer.token_address FROM transfers AS transfer WHERE transfer.chain_id=$1 AND transfer.block_number>$2
    UNION ALL
    SELECT token.token_address FROM tokens AS token JOIN (
        SELECT mint.pair_address FROM pool_mints AS mint WHERE mint.chain_id=$1 AND mint.block_number>$2
        UNION SELECT burn.pair_address FROM pool_burns AS burn WHERE burn.chain_id=$1 AND burn.block_number>$2
        UNION SELECT swap.pair_address FROM pool_swaps AS swap WHERE swap.chain_id=$1 AND swap.block_number>$2
        UNION SELECT sync.pair_address FROM pool_syncs AS sync WHERE sync.chain_id=$1 AND sync.block_number>$2
    ) AS pairs ON pairs.pair_address=token.lp_pair WHERE token.chain_id=$1
) AS affected ORDER BY token_address
`

type AffectedTokensAboveParams struct {
	ChainID     int64
	BlockNumber int64
}

func (q *Queries) AffectedTokensAbove(ctx context.Context, arg AffectedTokensAboveParams) ([]Address, error) {
	rows, err := q.db.Query(ctx, affectedTokensAbove, arg.ChainID, arg.BlockNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Address{}
	for rows.Next() {
		var token_address Address
		if err := rows.Scan(&token_address); err != nil {
			return nil, err
		}
		items = append(items, token_address)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const completeIndexerReorg = `-- name: CompleteIndexerReorg :exec
UPDATE indexer_reorgs SET outcome='recovered', completed_at=now()
WHERE reorg_id=$1 AND outcome='open'
`

func (q *Queries) CompleteIndexerReorg(ctx context.Context, reorgID int64) error {
	_, err := q.db.Exec(ctx, completeIndexerReorg, reorgID)
	return err
}

const deleteCreatorFeeClaimsAbove = `-- name: DeleteCreatorFeeClaimsAbove :execrows
DELETE FROM creator_fee_claims WHERE chain_id=$1 AND block_number>$2
`

type DeleteCreatorFeeClaimsAboveParams struct {
	ChainID     int64
	BlockNumber int64
}

func (q *Queries) DeleteCreatorFeeClaimsAbove(ctx context.Context, arg DeleteCreatorFeeClaimsAboveParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCreatorFeeClaimsAbove, arg.ChainID, arg.BlockNumber)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteEngineConfigurationsAbove = `-- name: DeleteEngineConfigurationsAbove :execrows
DELETE FROM engine_configurations WHERE chain_id=$1 AND block_number>$2
`

type DeleteEngineConfigurationsAboveParams struct {
	ChainID     int64
	BlockNumber int64
}

func (q *Queries) DeleteEngineConfigurationsAbove(ctx context.Context, arg DeleteEngineConfigurationsAboveParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEngineConfigurationsAbove, arg.ChainID, arg.BlockNumber)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteFutureDefaultsConfigurationsAbove = `-- name: DeleteFutureDefaultsConfigurationsAbove :execrows
DELETE FROM future_defaults_configurations WHERE chain_id=$1 AND block_number>$2
`

type DeleteFutureDefaultsConfigurationsAboveParams struct {
	ChainID     int64
	BlockNumber int64
}

func (q *Queries) DeleteFutureDefaultsConfigurationsAbove(ctx context.Context, arg DeleteFutureDefaultsConfigurationsAboveParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFutureDefaultsConfigurationsAbove, arg.ChainID, arg.BlockNumber)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteFutureTreasuryConfigurationsAbove = `-- name: DeleteFutureTreasuryConfigurationsAbove :execrows
DELETE FROM future_treasury_configurations WHERE chain_id=$1 AND block_number>$2
`

type DeleteFutureTreasuryConfigurationsAboveParams struct {
	ChainID     int64
	BlockNumber int64
}

func (q *Queries) DeleteFutureTreasuryConfigurationsAbove(ctx context.Context, arg DeleteFutureTreasuryConfigurationsAboveParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFutureTreasuryConfigurationsAbove, arg.ChainID, arg.BlockNumber)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteGraduationsAbove = `-- name: DeleteGraduationsAbove :execrows
DELETE FROM graduations WHERE chain_id=$1 AND block_number>$2
`

type DeleteGraduationsAboveParams struct {
	ChainID     int64
	BlockNumber int64
}

func (q *Queries) DeleteGraduationsAbove(ctx context.Context, arg DeleteGraduationsAboveParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGraduationsAbove, arg.ChainID, arg.BlockNumber)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteIndexedBlocksAbove = `-- name: DeleteIndexedBlocksAbove :execrows
DELETE FROM indexed_blocks WHERE chain_id=$1 AND block_number>$2
`

type DeleteIndexedBlocksAboveParams struct {
	ChainID     int64
	BlockNumber int64
}

func (q *Queries) DeleteIndexedBlocksAbove(ctx context.Context, arg DeleteIndexedBlocksAboveParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteIndexedBlocksAbove, arg.ChainID, arg.BlockNumber)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteLaunchFeeClaimsAbove = `-- name: DeleteLaunchFeeClaimsAbove :execrows
DELETE FROM launch_fee_claims WHERE chain_id=$1 AND block_number>$2
`

type DeleteLaunchFeeClaimsAboveParams struct {
	ChainID     int64
	BlockNumber int64
}

func (q *Queries) DeleteLaunchFeeClaimsAbove(ctx context.Context, arg DeleteLaunchFeeClaimsAboveParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLaunchFeeClaimsAbove, arg.ChainID, arg.BlockNumber)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteLaunchPauseEventsAbove = `-- name: DeleteLaunchPauseEventsAbove :execrows
DELETE FROM launch_pause_events WHERE chain_id=$1 AND block_number>$2
`

type DeleteLaunchPauseEventsAboveParams struct {
	ChainID     int64
	BlockNumber int64
}

func (q *Queries) DeleteLaunchPauseEventsAbove(ctx context.Context, arg DeleteLaunchPauseEventsAboveParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLaunchPauseEventsAbove, arg.ChainID, arg.BlockNumber)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePoolBurnsAbove = `-- name: DeletePoolBurnsAbove :execrows
DELETE FROM pool_burns WHERE chain_id=$1 AND block_number>$2
`

type DeletePoolBurnsAboveParams struct {
	ChainID     int64
	BlockNumber int64
}

func (q *Queries) DeletePoolBurnsAbove(ctx context.Context, arg DeletePoolBurnsAboveParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePoolBurnsAbove, arg.ChainID, arg.BlockNumber)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePoolMintsAbove = `-- name: DeletePoolMintsAbove :execrows
DELETE FROM pool_mints WHERE chain_id=$1 AND block_number>$2
`

type DeletePoolMintsAboveParams struct {
	ChainID     int64
	BlockNumber int64
}

func (q *Queries) DeletePoolMintsAbove(ctx context.Context, arg DeletePoolMintsAboveParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePoolMintsAbove, arg.ChainID, arg.BlockNumber)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePoolSwapsAbove = `-- name: DeletePoolSwapsAbove :execrows
DELETE FROM pool_swaps WHERE chain_id=$1 AND block_number>$2
`

type DeletePoolSwapsAboveParams struct {
	ChainID     int64
	BlockNumber int64
}

func (q *Queries) DeletePoolSwapsAbove(ctx context.Context, arg DeletePoolSwapsAboveParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePoolSwapsAbove, arg.ChainID, arg.BlockNumber)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePoolSyncsAbove = `-- name: DeletePoolSyncsAbove :execrows
DELETE FROM pool_syncs WHERE chain_id=$1 AND block_number>$2
`

type DeletePoolSyncsAboveParams struct {
	ChainID     int64
	BlockNumber int64
}

func (q *Queries) DeletePoolSyncsAbove(ctx context.Context, arg DeletePoolSyncsAboveParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePoolSyncsAbove, arg.ChainID, arg.BlockNumber)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteProtocolFeeClaimsAbove = `-- name: DeleteProtocolFeeClaimsAbove :execrows
DELETE FROM protocol_fee_claims WHERE chain_id=$1 AND block_number>$2
`

type DeleteProtocolFeeClaimsAboveParams struct {
	ChainID     int64
	BlockNumber int64
}

func (q *Queries) DeleteProtocolFeeClaimsAbove(ctx context.Context, arg DeleteProtocolFeeClaimsAboveParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProtocolFeeClaimsAbove, arg.ChainID, arg.BlockNumber)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRefundClaimsAbove = `-- name: DeleteRefundClaimsAbove :execrows
DELETE FROM refund_claims WHERE chain_id=$1 AND block_number>$2
`

type DeleteRefundClaimsAboveParams struct {
	ChainID     int64
	BlockNumber int64
}

func (q *Queries) DeleteRefundClaimsAbove(ctx context.Context, arg DeleteRefundClaimsAboveParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRefundClaimsAbove, arg.ChainID, arg.BlockNumber)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRefundCreditsAbove = `-- name: DeleteRefundCreditsAbove :execrows
DELETE FROM refund_credits WHERE chain_id=$1 AND block_number>$2
`

type DeleteRefundCreditsAboveParams struct {
	ChainID     int64
	BlockNumber int64
}

func (q *Queries) DeleteRefundCreditsAbove(ctx context.Context, arg DeleteRefundCreditsAboveParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRefundCreditsAbove, arg.ChainID, arg.BlockNumber)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTokenLaunchesAbove = `-- name: DeleteTokenLaunchesAbove :execrows
DELETE FROM token_launches WHERE chain_id=$1 AND block_number>$2
`

type DeleteTokenLaunchesAboveParams struct {
	ChainID     int64
	BlockNumber int64
}

func (q *Queries) DeleteTokenLaunchesAbove(ctx context.Context, arg DeleteTokenLaunchesAboveParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTokenLaunchesAbove, arg.ChainID, arg.BlockNumber)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTradesAbove = `-- name: DeleteTradesAbove :execrows
DELETE FROM trades WHERE chain_id=$1 AND block_number>$2
`

type DeleteTradesAboveParams struct {
	ChainID     int64
	BlockNumber int64
}

func (q *Queries) DeleteTradesAbove(ctx context.Context, arg DeleteTradesAboveParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTradesAbove, arg.ChainID, arg.BlockNumber)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTradingPauseEventsAbove = `-- name: DeleteTradingPauseEventsAbove :execrows
DELETE FROM trading_pause_events WHERE chain_id=$1 AND block_number>$2
`

type DeleteTradingPauseEventsAboveParams struct {
	ChainID     int64
	BlockNumber int64
}

func (q *Queries) DeleteTradingPauseEventsAbove(ctx context.Context, arg DeleteTradingPauseEventsAboveParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTradingPauseEventsAbove, arg.ChainID, arg.BlockNumber)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTransfersAbove = `-- name: DeleteTransfersAbove :execrows
DELETE FROM transfers WHERE chain_id=$1 AND block_number>$2
`

type DeleteTransfersAboveParams struct {
	ChainID     int64
	BlockNumber int64
}

func (q *Queries) DeleteTransfersAbove(ctx context.Context, arg DeleteTransfersAboveParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTransfersAbove, arg.ChainID, arg.BlockNumber)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findCommonAncestor = `-- name: FindCommonAncestor :one
SELECT block_number, block_hash
FROM indexed_blocks
WHERE chain_id = $1 AND block_hash = ANY($2::bytea[])
ORDER BY block_number DESC
LIMIT 1
`

type FindCommonAncestorParams struct {
	ChainID int64
	Column2 [][]byte
}

type FindCommonAncestorRow struct {
	BlockNumber int64
	BlockHash   Hash
}

func (q *Queries) FindCommonAncestor(ctx context.Context, arg FindCommonAncestorParams) (FindCommonAncestorRow, error) {
	row := q.db.QueryRow(ctx, findCommonAncestor, arg.ChainID, arg.Column2)
	var i FindCommonAncestorRow
	err := row.Scan(&i.BlockNumber, &i.BlockHash)
	return i, err
}

const recordIndexerReorg = `-- name: RecordIndexerReorg :one
INSERT INTO indexer_reorgs (
 chain_id, deployment_id, detected_tip_number, detected_tip_hash,
 common_ancestor_number, common_ancestor_hash, depth, detected_at, outcome
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,'open')
RETURNING reorg_id
`

type RecordIndexerReorgParams struct {
	ChainID              int64
	DeploymentID         string
	DetectedTipNumber    int64
	DetectedTipHash      Hash
	CommonAncestorNumber int64
	CommonAncestorHash   Hash
	Depth                int64
	DetectedAt           pgtype.Timestamptz
}

func (q *Queries) RecordIndexerReorg(ctx context.Context, arg RecordIndexerReorgParams) (int64, error) {
	row := q.db.QueryRow(ctx, recordIndexerReorg,
		arg.ChainID,
		arg.DeploymentID,
		arg.DetectedTipNumber,
		arg.DetectedTipHash,
		arg.CommonAncestorNumber,
		arg.CommonAncestorHash,
		arg.Depth,
		arg.DetectedAt,
	)
	var reorg_id int64
	err := row.Scan(&reorg_id)
	return reorg_id, err
}
