// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sync.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSyncState = `-- name: GetSyncState :one
SELECT
    chain_id, deployment_id,
    observed_number, observed_hash, observed_at,
    safe_number, safe_hash, safe_at,
    finalized_number, finalized_hash, finalized_at
FROM sync_state
WHERE chain_id = $1 AND deployment_id = $2
`

type GetSyncStateParams struct {
	ChainID      int64
	DeploymentID string
}

func (q *Queries) GetSyncState(ctx context.Context, arg GetSyncStateParams) (SyncState, error) {
	row := q.db.QueryRow(ctx, getSyncState, arg.ChainID, arg.DeploymentID)
	var i SyncState
	err := row.Scan(
		&i.ChainID,
		&i.DeploymentID,
		&i.ObservedNumber,
		&i.ObservedHash,
		&i.ObservedAt,
		&i.SafeNumber,
		&i.SafeHash,
		&i.SafeAt,
		&i.FinalizedNumber,
		&i.FinalizedHash,
		&i.FinalizedAt,
	)
	return i, err
}

const upsertSyncState = `-- name: UpsertSyncState :one
INSERT INTO sync_state (
    chain_id, deployment_id,
    observed_number, observed_hash, observed_at,
    safe_number, safe_hash, safe_at,
    finalized_number, finalized_hash, finalized_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (chain_id, deployment_id) DO UPDATE
SET observed_number = EXCLUDED.observed_number,
    observed_hash = EXCLUDED.observed_hash,
    observed_at = EXCLUDED.observed_at,
    safe_number = EXCLUDED.safe_number,
    safe_hash = EXCLUDED.safe_hash,
    safe_at = EXCLUDED.safe_at,
    finalized_number = EXCLUDED.finalized_number,
    finalized_hash = EXCLUDED.finalized_hash,
    finalized_at = EXCLUDED.finalized_at
RETURNING
    chain_id, deployment_id,
    observed_number, observed_hash, observed_at,
    safe_number, safe_hash, safe_at,
    finalized_number, finalized_hash, finalized_at
`

type UpsertSyncStateParams struct {
	ChainID         int64
	DeploymentID    string
	ObservedNumber  pgtype.Int8
	ObservedHash    *Hash
	ObservedAt      pgtype.Timestamptz
	SafeNumber      pgtype.Int8
	SafeHash        *Hash
	SafeAt          pgtype.Timestamptz
	FinalizedNumber pgtype.Int8
	FinalizedHash   *Hash
	FinalizedAt     pgtype.Timestamptz
}

func (q *Queries) UpsertSyncState(ctx context.Context, arg UpsertSyncStateParams) (SyncState, error) {
	row := q.db.QueryRow(ctx, upsertSyncState,
		arg.ChainID,
		arg.DeploymentID,
		arg.ObservedNumber,
		arg.ObservedHash,
		arg.ObservedAt,
		arg.SafeNumber,
		arg.SafeHash,
		arg.SafeAt,
		arg.FinalizedNumber,
		arg.FinalizedHash,
		arg.FinalizedAt,
	)
	var i SyncState
	err := row.Scan(
		&i.ChainID,
		&i.DeploymentID,
		&i.ObservedNumber,
		&i.ObservedHash,
		&i.ObservedAt,
		&i.SafeNumber,
		&i.SafeHash,
		&i.SafeAt,
		&i.FinalizedNumber,
		&i.FinalizedHash,
		&i.FinalizedAt,
	)
	return i, err
}
